# fly.toml app configuration file generated for half-marathon on 2024-04-24T00:29:04-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'half-marathon'
primary_region = 'ewr'

[build]

[env]
  MONGODB_URI='mongodb+srv://addisonwest98:LFUM00Cczrvd7Crt@cluster0.hlkgmrc.mongodb.net/half-marathon-countdown?retryWrites=true&w=majority&appName=Cluster0'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
